### ISSUE TITLE
qt code in the daemon

### ISSUE THREAD

**Issue by pallas1** [CryptoCoderz/Espers#1]
init.cpp:31:23: fatal error: QTextStream: No such file or directory

while doing make -f makefile.unix from src/

**Comment by CryptoCoderz** [comment]
Please check v0.8.4.2 Patch 3's commit as it was applied as a fix for the compilation issue.

Details:
#ifdef Q_OS_WIN
    //TODO: CORRECT THIS
    QString runcheck = QDir::homePath() + "/AppData/Roaming/ESP/chk.file";
    QString runcheck = QDir::currentPath() + "/chk.file";
    QFile rcheck(runcheck);
    if(rcheck.open(QIODevice::ReadWrite))
    {
    QTextStream saturate(&rcheck);
    saturate << "Temp File that flags launcher" << endl;
    }
#endif

**Comment by pallas1** [comment]
Same problem in db.cpp

**Comment by CryptoCoderz** [comment]
Got it, working on it.

**Comment by CryptoCoderz** [comment]
Corrected the second file. Double checked to make sure that the daemon files are defined for windows now.
