### ISSUE TITLE
No deposits into new wallet from Exchange

### ISSUE THREAD

**Issue by GithubEspers** [CryptoCoderz/Espers#16]
Hi - I had my Espers coins in Nova Exchange which I transferred yesterday (11/02/17) to my updated wallet on my Mac computer. Since yesterday I still haven’t seen the deposit to my wallet and I am getting very frustrated. I posted messages on twitter seeking help but so far I am still waiting. Can you please assist me with this issue? I communicates with Nova Exchange and they directed back to Espers because this seems to be a wallet issue. The funds have cleared successfully from Nova Exchange.

Transaction ID: | 9ec98a02ee62cfb9dffa40c8bbe0c552c76ad30989890380532cfe4ffa266239
-- | --

Transaction ID: | 97064bee0192f56b3b0df381831ed16548f198a0eab35a277f2ad2bb4e223b44
-- | --

Please advise at your earliest convenience because Nova Exchange will be closing and I don't want to lose my investments.

I am using the latest wallet and running MacOS Sierra Version 10.12.6

Best regards,

Michael

**Comment by GithubEspers** [comment]
I am using the latest wallet and running MacOS Sierra Version 10.12.6

**Comment by kartonikpl** [comment]
I have the same problem

Transaction ID:	9d3336d7f1fc26b9f9a6d3a1120a20c37c29a8eaecbc4ec54f2b648bb2184820

is not on my wallet

**Comment by kartonikpl** [comment]
My wallet win Espers-qt-v0.8.6.9

**Comment by kartonikpl** [comment]
Problem solved 
update wallet:
https://mega.nz/#!q9sDWQoY!zaKbTEUl8U_4ZDP-8CmABNEjMMA52bMgICGnn0Y9Riw

**Comment by kartonikpl** [comment]
For MacOS 
Espers-Qt-Mac-v0.8.6.4-Patch 0.zip
https://mega.nz/#!fx8gkZAK!IH1qkgPVPReI2-srf_8LBU3yJRYavnA3lxyjcAL9Vkw

**Comment by crypto101-info** [comment]
I had the same problem. The blockchain got split and my wallet, like many, got on the wrong end of it. I followed these steps to get to the right blockchain: https://blog.espers.io/using-the-snapshot-d8eb6d1cb3f6. Worked for me, funds finally showed up in the wallet.

**Comment by CryptoCoderz** [comment]
The blockchain underwent numerous updates since the November issues began which depricated all older clients/wallets. 

Your coins are retrievable from the exchange that you have/had them on as long as you update and sync to the official blockchain (which isn't hard to do now)

Closing issue as this has since been resolved with recent updates and all listed exchanges are on the latest update as well.
