### ISSUE TITLE
Unable to compile latest version on ubuntu

### ISSUE THREAD

**Issue by GuusSeldenthuis** [CryptoCoderz/Espers#19]
While building I get this error: hmq1725/blake.c:1119: fatal error: opening dependency file obj/hmq1725/blake.d: No such file or directory.

**Comment by oritwoen** [comment]
In src dir:

`mkdir obj obj/zerocoin `

**Comment by GuusSeldenthuis** [comment]
Didn't solve the issue.

**Comment by CryptoCoderz** [comment]
Please provide the following info so we can better assist you:

- Ubuntu OS version
- GitHub repo version (last commit pulled down to build from)
- List of steps taken in the attempt to compile the program

Thank you,
-CryptoCoderz
