### ISSUE TITLE
Linux Build failed

### ISSUE THREAD

**Issue by LeChuckDE** [CryptoCoderz/Espers#2]
like nealy all other wallet clones there is missing chmod +x at ./src/libleveldb/build_detect_platform

**Comment by CryptoCoderz** [comment]
We've had no issue using the github source and building on Linux.

Please advise if you'd like assistance

**Comment by LeChuckDE** [comment]
The solution is named in my posting. 
On ubuntu 15.10 and 14.04 you need to do a chmod +x at file ./src/libleveldb/buildf_detect_plattform first

**Comment by buzztiaan** [comment]
it also lacks a src/obj directory , needed to mkdir it

**Comment by CryptoCoderz** [comment]
CtGiant has resolved the issues. Please refer to the latest commit for further details
