### ISSUE TITLE
Nodes outdated

### ISSUE THREAD

**Issue by bitcoinx2** [CryptoCoderz/Espers#21]
The wallet will not start syncing automatically unless nodes from https://espstats.net/download/addnodes.txt are inserted into the Espers.conf file. These nodes should be included by default, so that newbies won't have any problems using the wallet.

**Comment by CryptoCoderz** [comment]
Issue no. 21 (Nodes outdated) has been added to the next update scheduled for commit.

**Comment by CryptoCoderz** [comment]
Closing issue, nodes updated. (Thank you for the issue submission)
