### ISSUE TITLE
EXCEPTION: NSt8ios_base7failureB5cxx11E

### ISSUE THREAD

**Issue by leprecon73** [CryptoCoderz/Espers#24]
$ ./Espers-qt 

************************
EXCEPTION: NSt8ios_base7failureB5cxx11E       
CDataStream::read() : end of data: iostream error       
Espers in Runaway exception       

Segmentation fault
-------------------------------------------------------------------
$ uname -a
Linux pit-desktop 4.8.0-040800-generic #201610022031 SMP Mon Oct 3 00:32:57 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by CryptoCoderz** [comment]
Hello @leprecon73 

The issue you're experiencing is in regards to the latest update and github commit. Please clear your Espers data directory and then run the wallet as this will resolve your issue (upon full resync).

Thank you for contacting us and posting an issue,
- The CryptoCoderz Team
