### ISSUE TITLE
Windows Wallet (0.8.7.4) - Fatal Error

### ISSUE THREAD

**Issue by jbnl** [CryptoCoderz/Espers#32]
![espers](https://user-images.githubusercontent.com/37104766/47495266-fc34bd00-d853-11e8-9ab0-27efc3780b57.png)

Receiving this error with the the current Windows download from your website.

**Comment by CryptoCoderz** [comment]
Please resync using this method: https://blog.espers.io/using-the-snapshot-d8eb6d1cb3f6
