### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rpokupec** [CryptoCoderz/Espers#34]
Hi,

Cannot install latest Espers v0.8.7.5 Update-0 Patch-0 wallet on win 10.
I get runaway exception.
![error](https://user-images.githubusercontent.com/26463706/47962761-b6c97a00-e021-11e8-8f54-56859f83f64a.png)

**Comment by CryptoCoderz** [comment]
This issue is a duplicate of: https://github.com/CryptoCoderz/Espers/issues/32

Please resync using this method: https://blog.espers.io/using-the-snapshot-d8eb6d1cb3f6
