### ISSUE TITLE
0.8.7.4, 0.8.7.5 Ubuntu headless daemon compile error

### ISSUE THREAD

**Issue by moppidoo** [CryptoCoderz/Espers#35]
Hi,

I'm trying to compile the daemon on Ubuntu 16.04 LTS (having previously succeeded compiling the QT wallet GUI, 0.8.7.4 alpha 0), and I'm stuck on the part where the compilation errored out on miner.cpp.

I followed steps in both build-unix.txt as well as https://blog.espers.io/getting-espers-wallet-and-setting-it-up-1ac91c0bfd21 to no avail.

It'd be great to be able to solve the issue as I'm fairly new at these things (linux and compiling code). thanks in advance!!

`miner.cpp: In function ‘CBlock* CreateNewBlock(CReserveKey&, bool, int64_t*)’:
miner.cpp:108:5: error: ‘unique_ptr’ was not declared in this scope
     unique_ptr<CBlock> pblock(new CBlock());
     ^
miner.cpp:108:5: note: suggested alternatives:
In file included from /usr/include/boost/thread/csbl/memory/unique_ptr.hpp:16:0,
                 from /usr/include/boost/thread/future.hpp:40,
                 from /usr/include/boost/thread.hpp:24,
                 from util.h:24,
                 from chainparams.h:11,
                 from protocol.h:13,
                 from net.h:21,
                 from blockparams.h:7,
                 from miner.cpp:8:
/usr/include/boost/move/unique_ptr.hpp:346:7: note:   ‘boost::movelib::unique_ptr’
 class unique_ptr
       ^
/usr/include/boost/move/unique_ptr.hpp:346:7: note:   ‘boost::movelib::unique_ptr’
miner.cpp:108:22: error: expected primary-expression before ‘>’ token
     unique_ptr<CBlock> pblock(new CBlock());
                      ^
miner.cpp:108:43: error: ‘pblock’ was not declared in this scope
     unique_ptr<CBlock> pblock(new CBlock());
                                           ^
miner.cpp: In function ‘void ThreadStakeMiner(CWallet*)’:
miner.cpp:572:9: error: ‘unique_ptr’ was not declared in this scope
         unique_ptr<CBlock> pblock(CreateNewBlock(reservekey, true, &nFees));
         ^
miner.cpp:572:9: note: suggested alternatives:
In file included from /usr/include/boost/thread/csbl/memory/unique_ptr.hpp:16:0,
                 from /usr/include/boost/thread/future.hpp:40,
                 from /usr/include/boost/thread.hpp:24,
                 from util.h:24,
                 from chainparams.h:11,
                 from protocol.h:13,
                 from net.h:21,
                 from blockparams.h:7,
                 from miner.cpp:8:
/usr/include/boost/move/unique_ptr.hpp:346:7: note:   ‘boost::movelib::unique_ptr’
 class unique_ptr
       ^
/usr/include/boost/move/unique_ptr.hpp:346:7: note:   ‘boost::movelib::unique_ptr’
miner.cpp:572:26: error: expected primary-expression before ‘>’ token
         unique_ptr<CBlock> pblock(CreateNewBlock(reservekey, true, &nFees));
                          ^
miner.cpp:572:75: error: ‘pblock’ was not declared in this scope
         unique_ptr<CBlock> pblock(CreateNewBlock(reservekey, true, &nFees));
                                                                           ^
In file included from txdb-leveldb.h:9:0,
                 from txdb.h:9,
                 from miner.cpp:9:
main.h: At global scope:
main.h:44:27: warning: ‘MAX_STANDARD_TX_SIZE’ defined but not used [-Wunused-variable]
 static const unsigned int MAX_STANDARD_TX_SIZE = MAX_BLOCK_SIZE_GEN/5;
                           ^
main.h:50:21: warning: ‘MAX_TX_SIGOPS’ defined but not used [-Wunused-variable]
 static unsigned int MAX_TX_SIGOPS = MAX_BLOCK_SIGOPS/5;
                     ^
main.h:52:27: warning: ‘MAX_ORPHAN_TRANSACTIONS’ defined but not used [-Wunused-variable]
 static const unsigned int MAX_ORPHAN_TRANSACTIONS = MAX_BLOCK_SIZE/100;
                           ^
makefile.unix:202: recipe for target 'obj/miner.o' failed
make: *** [obj/miner.o] Error 1`
![image](https://user-images.githubusercontent.com/9251248/48656147-f310c780-ea70-11e8-81d4-7e8cae93aa61.png)

**Comment by CryptoCoderz** [comment]
Thank you very much for submitting this issue.

The reason you're experiencing this is because we have updated the codebase to use "unique_ptr" which is compatible with newer compilers (Ubuntu 18.04+, Updated 16.04's, and many other Linux distros since much earlier)

We're currently working on a compatibility release for deprecated compilers which will be released soon.
Will follow up with github commit and reference to such.

**Comment by CryptoCoderz** [comment]
Followup:

Please review this commit in regards to the changes made for compatibility with older gcc compilers.
https://github.com/CryptoCoderz/Espers/commit/94057da255543b52729f258849eea9d8e057c68d

As of this commit this issue has been resolved and will build on either newer or older gcc compilers without warnings or errors.
