### ISSUE TITLE
error in README.md

### ISSUE THREAD

**Issue by Austpool** [CryptoCoderz/Espers#40]
small error of a missing space in Dependencies build and link part.
at the end "cd~", not "cd ~"

**Comment by CryptoCoderz** [comment]
Ah, thank you so much for catching this! Correcting it now.

**Comment by CryptoCoderz** [comment]
Corrected with: https://github.com/CryptoCoderz/Espers/commit/43cfde3f238b696ce0ce28cbb2ea8d65fa5377e8

Thank you again!
