### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by mazi8** [CryptoCoderz/Espers#45]
Hi,
I've done the snapshot. 
The wallet makes 18 connections yet it is stuck at 99.89 % 
and it is not syncking ( wallet has been open for few days). 
What I am I doing wrong?

**Comment by CryptoCoderz** [comment]
Hello Mazi8,

Thank you for reaching out to us and we look forward to resolving your issue. 
Please join our discord and head over to the #wallet-help channel.

If you are not already in our Discord you may use this invite like to join up: https://discord.gg/HhhUD2f

Looking forward to hearing from you,
- Jon (CryptoCoderz)

**Comment by CryptoCoderz** [comment]
User has joined our Discord server, closing issue as this will be resolved by the team working with the end user.
