### ISSUE TITLE
Not connecting to any nodes after block 667350

### ISSUE THREAD

**Issue by tatdig** [CryptoCoderz/Espers#46]
Ver v0.8.7.5-Patch 11 Alpha wallet stop sync and nodes not available

**Comment by CryptoCoderz** [comment]
Hello @tatdig can you please post the last part of your debug log? This way we can see exactly what your wallet is doing when it's dropping nodes

**Comment by CryptoCoderz** [comment]
Also it would be great if you joined our Discord as we can help you better there! https://discord.gg/cn3AfPS

**Comment by tatdig** [comment]
Problem solved by downgrade to older version of the wallet. Noticed that when requested getmininginfo there was exception. It is all good for me. But your latest release is not working.
