### ISSUE TITLE
incorrect number of coins in wallet, not updated number of coins after stake

### ISSUE THREAD

**Issue by dxgold** [CryptoCoderz/Espers#53]
incorrect number of coins in wallet, not updated number of coins after stake. got incorrect number of coins when synced from snapshot, only after restart of wallet got correct number of coins.

**Comment by CryptoCoderz** [comment]
Resolved as of: https://github.com/CryptoCoderz/Espers/commit/56a247559076fade8b3db197379eb85e8cc86b54

**Comment by dxgold** [comment]
great!
