### ISSUE TITLE
SSE is not used on 32bit x86 Linux GCC

### ISSUE THREAD

**Issue by bitcoinx2** [CryptoCoderz/Espers#8]
By default, SSE is not enabled on Linux x86 which leads to slightly wrong output of the Terminal_Velocity_RateX() function.

Fix: Set the compiler flags "-msse -msse2 -mfpmath=sse" during compilation. Maybe this can be enabled through the qmake .pro file?

Also, it should be noted that the output of such function should ideally not depend on hardware-specific details or compiler settings! When using floating point math, the results should be checked or processed in such a way that minor offsets don't matter. Floating point math does NOT provide any hard guarantees to the output values!

**Comment by CryptoCoderz** [comment]
We've discussed this and found this to be a environment variable of the particular Linux OS

**Comment by bitcoinx2** [comment]
This is still not solved. The solution we found for Debian was specifying QMAKESPEC=linux-g++-32. Now -msse2 is added to the makefile, but it still needs to be enabled by default by using -mfpmath=sse. See https://software.intel.com/en-us/blogs/2012/09/26/gcc-x86-performance-hints

While inserting this manually into the Makefile after running qmake solves the problem, please also include it into the build process by default.

Still I believe that using unchecked floating point math to calculate Integer numbers that need to be the same across all systems is a very bad idea. ;) See https://en.wikipedia.org/wiki/Floating-point_arithmetic#Minimizing_the_effect_of_accuracy_problems
